# Generated by Django 4.2.16 on 2024-10-17 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_to',
            field=models.DateField(default=datetime.date(2025, 10, 17)),
        ),
        migrations.AddField(
            model_name='room',
            name='available_to',
            field=models.DateField(default=datetime.date(2025, 10, 17)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
