# Generated by Django 5.1.2 on 2024-10-21 20:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_available_to_room_available_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='users_listings',
        ),
        migrations.AddField(
            model_name='listing',
            name='host',
            field=models.ForeignKey(default=2, limit_choices_to={'is_host': True}, on_delete=django.db.models.deletion.CASCADE, related_name='users_listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_to',
            field=models.DateField(default=datetime.date(2025, 10, 22)),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_to',
            field=models.DateField(default=datetime.date(2025, 10, 22)),
        ),
    ]
