# Generated by Django 5.1.2 on 2024-10-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_users_listings_listing_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel_rooms',
            new_name='rooms',
        ),
        migrations.AlterField(
            model_name='listing',
            name='host',
            field=models.ForeignKey(limit_choices_to={'is_host': True}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
